services:
  - type: web
    name: tg-bot-drivingtraf
    env: python
    plan: free
    region: oregon
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        sync: false
        value: 3.11
      - key: PORT
        sync: false
        value: 8080
      - key: API_TOKEN
        sync: false
        value: 8163482962:AAFpdGrhJdGqTcklXAl93zSglXmK26hDTOg
